[project]
name = "xmusic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "keyboard>=0.13.5",
    "pysdl2>=0.9.17",
    "pysdl2-dll>=2.32.0",
    "tinytag>=2.1.1",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[dependency-groups]
dev = [
    "pyinstaller>=6.14.1",
]

[project.scripts]
xmusic = "xmusic:main"
